apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trigger-build
spec:
  steps:
    - env:
        - name: BUILD_CONFIG_WEBHOOK_PATH
          valueFrom:
            secretKeyRef:
              name: test-tekton
              key: webhook-url
      command:
        - curl
        - '-X'
        - POST
        - '-k'
        - $BUILD_CONFIG_WEBHOOK_PATH
      image: registry.redhat.io/ubi7/ubi-minimal
      name: ''
      resources: {}
