apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trigger-build
spec:
  steps:
    - name: install-requests
      script: |
        #!/usr/bin/env sh
        pip install requests
    - name: run-script
      env:
        - name: BUILD_CONFIG_WEBHOOK_PATH
          valueFrom:
            - secretKeyRef:
                name: test-tekton
                key: webhook-url
      script: |
        #!/usr/bin/env python
        import os
        import requests
        
        BUILD_CONFIG_PATH = os.environ["BUILD_CONFIG_WEBHOOK_PATH"]
        
        response = requests.post(BUILD_CONFIG_PATH)
        if response.status_code != 200:
            raise Exception("Build not triggered")

      image: registry.redhat.io/ubi8/python-38
      resources: { }
