apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: trigger-build
spec:
  steps:
    - name: run-script
      env:
        - name: BUILD_CONFIG_WEBHOOK_PATH
          valueFrom:
            secretKeyRef:
              name: test-tekton
              key: webhook-url
      script: |
        #!/usr/bin/env sh
        http_response=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST -k $BUILD_CONFIG_WEBHOOK_PATH)
        if [ $http_response != "200" ]; then
          exit 1
        fi

      image: registry.redhat.io/ubi8/ubi-minimal
      resources: { }
