name: Snyk Security

on:
  pull_request:
    branches: ["master"]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_INTEGRATION_VERSION: python-3.8
        with:
          command: test
